Solved issued with Drupal API Driver and Behat

diff --git a/.docksal/commands/behat b/.docksal/commands/behat
--- a/.docksal/commands/behat
+++ b/.docksal/commands/behat
@@ -1,2 +1,38 @@
-## Custom command description
-$PROJECT_ROOT/vendor/bin/behat
+#!/usr/bin/env bash
+
+## Run project's Behat tests.
+##
+## Usage: fin behat [--path=path] [arguments]
+##
+## path defaults to tests/behat
+
+# Environment variables passed from fin:
+#
+#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
+#   $VIRTUAL_HOST - (string) ex. projectname.docksal
+#   $DOCROOT - name of the docroot folder
+#   $DOCKER_RUNNING - (string) "true" or "false"
+
+params=''
+path='features'
+for i in "$@"; do
+	case "$i" in
+		--path=*)
+			path="${i#*=}"
+			;;
+		*)
+			params="$params$i "
+			;;
+	esac;
+done
+
+behat_yml_path="./behat.yml"
+if [[ ! -f "$behat_yml_path" ]]; then
+	echo "Could not find $behat_yml_path"
+	exit 1
+fi
+
+cd $PROJECT_ROOT
+
+# Launch Behat tests
+fin exec "vendor/bin/behat -p docker $params"
